// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqgdtqousmjhaeyggoqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxZ2R0cW91c21qaGFleWdnb3F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NzMyMjYsImV4cCI6MjA3MTI0OTIyNn0.FqwOhOweSovdIZOss5H_GRukUcrmKy-n209VwHIIbok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});